### ISSUE TITLE
Random crashes in `lol::SdlInputData::Tick`

### ISSUE THREAD

**Issue by samhocevar** [lolengine/lolengine#3]
Sometimes right after startup programs crash randomly. It looks like a race condition:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  operator[] (n=4, this=0x90) at ./lol/base/array.h:148
148         ASSERT(n >= 0 && (n < m_count || (!n && !m_count)),
(gdb) bt
#0  operator[] (n=4, this=0x90) at ./lol/base/array.h:148
#1  SetAxis (value=0, id=4, this=0x0) at ./input/input_internal.h:57
#2  lol::SdlInputData::Tick (this=0xf23850, seconds=<optimized out>) at platform/sdl/sdlinput.cpp:207
#3  0x00000000004658e2 in lol::TickerData::GameThreadTick () at ticker.cpp:353
#4  0x0000000000465dba in lol::TickerData::GameThreadMain (this=0x713ec0 <lol::tickerdata>) at ticker.cpp:161
#5  0x0000000000466875 in operator() (this=<optimized out>) at /usr/include/c++/4.9/functional:2439
#6  lol::thread_base::trampoline (data=<optimized out>) at ./sys/threadbase.h:293
#7  0x00007fc7f75ac0a4 in start_thread (arg=0x7fc7e4ff0700) at pthread_create.c:309
#8  0x00007fc7f6abf04d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by gbittoun** [comment]
Sorry, didn’t think that referencing the issue would close it. Reopening…
